### ISSUE TITLE
Button type is hardcoded

### ISSUE THREAD

**Issue by ZJvandeWeg** [flowforge/forge-ui-components#12]
### Current Behavior

https://github.com/flowforge/forge-ui-components/blob/f77dae2286feb05bd1b4b3898f13040cdde1d0d6/src/components/Button.vue#L2

### Expected Behavior

The type of button can also be "submit"

### Environment

- FlowForge version:
- Node.js version:
- npm version:
- Platform/OS:
- Browser:

**Comment by ZJvandeWeg** [comment]
@joepavitt It would be nice if there was the opportunity to just test if the output is what's expected.

**Comment by joepavitt** [comment]
By that, do you mean, type out some `html` example and see the direct output in browser? 

At the moment, our only option here is modifying the docs and seeing the output. It would be possible to have a `playground` environment, although would require a good chunk of time/resource in order to build it with the relevant security and validation of inputs.

**Comment by ZJvandeWeg** [comment]
> By that, do you mean, type out some html example and see the direct output in browser?

No, just plain tests. If I input some `.vue` I'd like to test the `type` property is set to whatever I wanted. Just a unit test really.

**Comment by joepavitt** [comment]
Ah, I'm with you. We are lacking unit testing across all frontend work at the moment.
